name: Compile Pascal App

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pascal
        run: choco install lazarus -y

      - name: Compile Pascal code
        run: fpc puzzle.pas

      - name: Show Executable
        run: dir
