name: Compile Pascal App

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Install MSVC build tools
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --passive"
          choco install cmake --install-arguments 'ADD_CMAKE_TO_PATH=System'

      - name: Install Pascal
        run: choco install lazarus -y

      - name: Free Pascal Compiler
        uses: suve/GHActions-FPC@v0.4.0
        with:
          source: puzzle.pas

      - name: Show Executable
        run: dir
