name: Compile Pascal App

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pascal
        run: choco install lazarus -y

      - name: Free Pascal Compiler
        uses: suve/GHActions-FPC@v0.4.0
        with:
          source: puzzle.pas

      - name: Show Executable
        run: dir
