name: Compile Pascal App

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Free Pascal
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install freepascal -y

      - name: Load Free Pascal
        run: refreshenv

      - name: Compile Pascal code
        run: fpc puzzle.pas

      - name: Show Executable
        run: dir
